services:
  postgres:
    image: postgres:16
    container_name: hubsesc-cms-postgres
    environment:
      POSTGRES_DB: hubsesc_cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
